from wxServices.Product import Product
from wxServices.User import User
from wxServices.Student import Student
from wxServices.Parent import Parent
from wxServices.Faculty import Faculty
from wxServices.Employee import Employee
from wxServices.Register import Register
from wxServices.Timetable import Timetable
from wxServices.XmlrpclibUtil import XmlrpclibUtil